spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projet_fin
    username: postgres
    password: IDvl/501
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update